apiVersion: v1
kind: Service
metadata:
  name: svc-pod1
spec:
  type: NodePort
  ports:
    - port: 80 #caso eu não defina porta, a target porta tbma ssume essa
      nodePort: 30000
  selector:
    app: primeiro-pod