apiVersion: v1
kind: Service
metadata:
  name: svc-pod1-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80 #caso eu não defina porta, a target porta tbm assume essa
      nodePort: 30001
      targetPort: 30000
  selector:
    app: primeiro-pod